project:
  type: website
  output-dir: docs

website:
  title: "Alexa Andrade"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - ProjectPage.qmd
      - Freeforall.qmd
      - Resume.qmd 
      
format:
  html:
    code-fold: true             # enables code folding
    code-summary: "Show code"   # label for the toggle button
    theme:
      light: trestles
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual








